PHYSICAL_PAGE_SIZE: int = 4096 # 4KB pages
ATTRIBUTE_SIZE: int = 8 # 64-bit integers

INVALID_OFFSET: int = -1
INVALID_RID: int = 0

NUMBER_OF_METADATA_COLUMNS = 2 # Only supporting Indirection and Schema Encoding for now

INDIRECTION_COLUMN = -1
SCHEMA_ENCODING_COLUMN = -2
RID_COLUMN = -3
TIMESTAMP_COLUMN = -4

MAX_BASE_PAGES_IN_PAGE_RANGE = 16