PHYSICAL_PAGE_SIZE: int = 4096 # 4KB pages
ATTRIBUTE_SIZE: int = 8 # 64-bit integers
INVALID_OFFSET: int = -1
INVALID_RID: int = 0
INDIRECTION_COLUMN = -1
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3