ATTRIBUTE_SIZE: int = 8  # 64-bit integers
INDIRECTION_COLUMN = -1
INVALID_SLOT_NUM: int = -1
BASE_RID = -2
INVALID_RID: int = 0
MAX_BASE_PAGES_IN_PAGE_RANGE = 16
NUMBER_OF_METADATA_COLUMNS = (
    3  # Only supporting Indirection and Schema Encoding for now
)
PHYSICAL_PAGE_SIZE: int = 4096  # 4KB pages
RID_COLUMN = -3
SCHEMA_ENCODING_COLUMN = -3
TIMESTAMP_COLUMN = -4
LOGICAL_DELETE = 0
START_BASE_RID = 1
START_TAIL_RID = -1
NUM_METADATA_COLS = 2
MAX_BUFFERPOOL_SIZE = 10000